# fly.toml app configuration file generated for cutout-ai-api on 2026-03-07T01:36:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cutout-ai-api'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '60s'
    method = 'get'
    path = '/api/health'
    protocol = 'http'

[[vm]]
  memory = '4gb'
  cpus = 1
  memory_mb = 4096
